---
title: "Build BCR Databases"
vignette: >
  %\VignetteIndexEntry{Build OmniPathR databases}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
author: "`r 'Author: Matthew Hung'`"
date: "`r paste('Last Updated:', format(Sys.Date(), '%Y/%m/%d'))`"
output:
  html_document:
    code_folding: hide
knitr:
  opts_chunk:
    collapse: true
    comment: '#>'
---
```{r}
library(tidyverse)
library(readxl)
```

## Sars-CoV-2
```{r}
covid_dab <- list()
```

### CoV-AbDab
```{r}
dab <- read.csv("./resources/Sars-CoV-2/20240208_CoV-AbDab.csv")
dab %>% head() %>% show()
```

```{r}
dab <- dab %>%
  filter(str_detect(Origin, "[Hh]uman")|str_detect(Origin, "[Mm]ouse")) %>%
  mutate(
    antigen = "Sars-CoV-2",
    ref_source = "CoV-AbDab",
    ref_data = Sources,
    ref_strain = `Binds.to`,
    ref_name = Name,
    ref_epitope = `Protein...Epitope`,
    ref_org = case_when(
        str_detect(Origin, "[Hh]uman") ~ "human",
        str_detect(Origin, "[Mm]ouse") ~ "mouse"),
    ref_heavyV = gsub(" .*", "", `Heavy.V.Gene`),
    ref_heavyJ = gsub(" .*", "", `Heavy.J.Gene`),
    ref_heavyCDR3 = paste0("C", `CDRH3`, "W"),
    ref_lightV = gsub(" .*", "", `Light.V.Gene`),
    ref_lightJ = gsub(" .*", "", `Light.J.Gene`),
    ref_lightCDR3 = paste0("C", `CDRL3`, "W")
  ) %>%
  dplyr::select(antigen, ref_strain, ref_source, ref_data, ref_name, ref_epitope, ref_org, ref_heavyV, ref_heavyJ, ref_heavyCDR3, ref_lightV, ref_lightJ, ref_lightCDR3) %>%
  distinct(ref_heavyV, ref_heavyJ, ref_heavyCDR3, ref_lightV, ref_lightJ, ref_lightCDR3, .keep_all = TRUE)
 
dim(dab)

covid_dab[[1]] <- dab
```

### LopezDeAssis_2023
```{r}
dab <- read.csv("./resources/Sars-CoV-2/LopezDeAssis_2023.csv")
dab <- dab %>%
  filter(str_detect(.[[1]], "^Spike_B_cell"))
dab %>% head() %>% show()
```

```{r}
dab <- dab %>%
  filter(str_detect(.[[1]], "^Spike")) %>%
  mutate(
    antigen = "Sars-CoV-2",
    ref_source = "LopezDeAssis_2023",
    ref_data = ref_source,
    ref_strain = "mRNA-1273",
    ref_name = `X`,
    ref_epitope = "S2P",
    ref_org = "human",
    ref_heavyV = v_call_VDJ_main,
    ref_heavyJ = j_call_VDJ_main,
    ref_heavyCDR3 = junction_aa_VDJ,
    ref_lightV = v_call_VJ_main,
    ref_lightJ = j_call_VJ_main,
    ref_lightCDR3 = junction_aa_VJ
  ) %>%
  dplyr::select(antigen, ref_strain, ref_source, ref_data, ref_name, ref_epitope, ref_org, ref_heavyV, ref_heavyJ, ref_heavyCDR3, ref_lightV, ref_lightJ, ref_lightCDR3) %>%
  distinct(ref_heavyV, ref_heavyJ, ref_heavyCDR3, ref_lightV, ref_lightJ, ref_lightCDR3, .keep_all = TRUE)
 
dim(dab)

covid_dab[[2]] <- dab
```

```{r}
covid_dab <- bind_rows(covid_dab)
write.csv(covid_dab, "./inst/extdata/Sars-CoV-2.csv", row.names = FALSE)
```


## Vaccinia
```{r}
vaccinia_dab <- list()
```

### Chappert_2022 IGH only
```{r}
dab <- read_excel("./resources/Vaccinia/Chappert_2022.xlsx", sheet = 3, skip = 2)
dab %>% head() %>% show()
```

```{r}
dab <- dab %>%
  mutate(
    antigen = "Vaccinia",
    ref_source = "Chappert_2022",
    ref_data = ref_source,
    ref_strain = "Vaccinia",
    ref_name = sequence_id,
    ref_epitope = "B5",
    ref_org = "human",
    ref_heavyV = gsub("\\*.*", "", v_call),
    ref_heavyJ = gsub("\\*.*", "", j_call),
    ref_heavyCDR3 = cdr3,
    ref_lightV = NA,
    ref_lightJ = NA,
    ref_lightCDR3 = NA
  ) %>%
  dplyr::select(antigen, ref_strain, ref_source, ref_data, ref_name, ref_epitope, ref_org, ref_heavyV, ref_heavyJ, ref_heavyCDR3, ref_lightV, ref_lightJ, ref_lightCDR3) %>%
  distinct(ref_heavyV, ref_heavyJ, ref_heavyCDR3, ref_lightV, ref_lightJ, ref_lightCDR3, .keep_all = TRUE)
 
dim(dab)

vaccinia_dab[[1]] <- dab
```


### Chappert_2022 IGH + IGL
```{r}
dab <- read_excel("./resources/Vaccinia/Chappert_2022.xlsx", sheet = 4, skip = 3)
dab %>% head() %>% show()
```

```{r}
dab <- dab %>%
  mutate(
    antigen = "Vaccinia",
    ref_source = "Chappert_2022",
    ref_data = ref_source,
    ref_strain = "Vaccinia",
    ref_name = cell_id,
    ref_epitope = "B5",
    ref_org = "human",
    ref_heavyV = gsub("\\*.*", "", `v_call...8`),
    ref_heavyJ = gsub("\\*.*", "", `j_call...10`),
    ref_heavyCDR3 = `cdr3...11`,
    ref_lightV = gsub("\\*.*", "", `v_call...16`),
    ref_lightJ = gsub("\\*.*", "", `j_call...17`),
    ref_lightCDR3 = `cdr3...18`
  ) %>%
  dplyr::select(antigen, ref_strain, ref_source, ref_data, ref_name, ref_epitope, ref_org, ref_heavyV, ref_heavyJ, ref_heavyCDR3, ref_lightV, ref_lightJ, ref_lightCDR3) %>%
  distinct(ref_heavyV, ref_heavyJ, ref_heavyCDR3, ref_lightV, ref_lightJ, ref_lightCDR3, .keep_all = TRUE)
 
dim(dab)

vaccinia_dab[[2]] <- dab
```




```{r}
vaccinia_dab <- bind_rows(vaccinia_dab)
write.csv(vaccinia_dab, "./inst/extdata/Vaccinia.csv", row.names = FALSE)
```